// Generated by Wrangler by running `wrangler types`

interface Env {
	FUNCTIONS_REGISTRY: KVNamespace;
	FUNCTIONS_CODE: KVNamespace;
	FUNCTIONS_API_KEYS: KVNamespace;
	ENVIRONMENT: "production";
	SERVICE_NAME: "functions.do";
	FUNCTION_EXECUTOR: DurableObjectNamespace /* FunctionExecutor */;
	FUNCTION_LOGS: DurableObjectNamespace /* FunctionLogs */;
	FSX: Fetcher;
	BASHX: Fetcher;
	ASSETS: Fetcher;
}
