# Emscripten CMake Toolchain File for Functions.do
# Generated by Functions.do C/C++ Compiler
#
# This toolchain file configures CMake to use Emscripten for compiling
# C/C++ code to WebAssembly.
#
# Usage:
#   cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/emscripten.cmake ..
#
# Prerequisites:
#   - Emscripten SDK installed and activated
#   - Environment variable EMSDK pointing to SDK root

# Specify the target system
set(CMAKE_SYSTEM_NAME Emscripten)
set(CMAKE_SYSTEM_VERSION 1)

# Find Emscripten
if(DEFINED ENV{EMSDK})
  set(EMSDK_ROOT "$ENV{EMSDK}")
elseif(EXISTS "/usr/local/emsdk")
  set(EMSDK_ROOT "/usr/local/emsdk")
elseif(EXISTS "$ENV{HOME}/emsdk")
  set(EMSDK_ROOT "$ENV{HOME}/emsdk")
else()
  message(FATAL_ERROR "Could not find Emscripten SDK. Set EMSDK environment variable.")
endif()

# Set compilers
set(CMAKE_C_COMPILER "${EMSDK_ROOT}/upstream/emscripten/emcc")
set(CMAKE_CXX_COMPILER "${EMSDK_ROOT}/upstream/emscripten/em++")
set(CMAKE_AR "${EMSDK_ROOT}/upstream/emscripten/emar" CACHE FILEPATH "Emscripten ar")
set(CMAKE_RANLIB "${EMSDK_ROOT}/upstream/emscripten/emranlib" CACHE FILEPATH "Emscripten ranlib")

# Specify file extensions
set(CMAKE_EXECUTABLE_SUFFIX ".wasm")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Emscripten-specific compiler flags for Functions.do
set(FUNCTIONS_DO_COMMON_FLAGS
  "-s STANDALONE_WASM=1"      # Produce standalone WASM
  "-s EXPORTED_RUNTIME_METHODS=[]"  # No runtime methods needed
  "-s ALLOW_MEMORY_GROWTH=1"  # Allow memory to grow
  "-s INITIAL_MEMORY=65536"   # Start with 64KB (1 page)
  "-s MAXIMUM_MEMORY=67108864" # Max 64MB
  "-s STACK_SIZE=16384"       # 16KB stack
  "-fno-exceptions"           # Disable C++ exceptions
  "-fno-rtti"                 # Disable RTTI
)

# Optimization flags for release builds
set(FUNCTIONS_DO_RELEASE_FLAGS
  "-O3"                       # Maximum optimization
  "-flto"                     # Link-time optimization
  "-s ASSERTIONS=0"           # Disable assertions
  "--closure 1"               # Run closure compiler
)

# Debug flags
set(FUNCTIONS_DO_DEBUG_FLAGS
  "-O0"                       # No optimization
  "-g"                        # Debug symbols
  "-s ASSERTIONS=2"           # Full assertions
)

# Apply common flags
string(REPLACE ";" " " COMMON_FLAGS_STR "${FUNCTIONS_DO_COMMON_FLAGS}")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${COMMON_FLAGS_STR}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMMON_FLAGS_STR}")

# Apply release flags
string(REPLACE ";" " " RELEASE_FLAGS_STR "${FUNCTIONS_DO_RELEASE_FLAGS}")
set(CMAKE_C_FLAGS_RELEASE "${CMAKE_C_FLAGS_RELEASE} ${RELEASE_FLAGS_STR}")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} ${RELEASE_FLAGS_STR}")

# Apply debug flags
string(REPLACE ";" " " DEBUG_FLAGS_STR "${FUNCTIONS_DO_DEBUG_FLAGS}")
set(CMAKE_C_FLAGS_DEBUG "${CMAKE_C_FLAGS_DEBUG} ${DEBUG_FLAGS_STR}")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} ${DEBUG_FLAGS_STR}")

# Helper function to create a Functions.do WASM module
function(functions_do_add_wasm_module TARGET_NAME)
  cmake_parse_arguments(PARSE_ARGV 1 ARG "" "OUTPUT_NAME" "SOURCES;EXPORTS")

  if(NOT ARG_OUTPUT_NAME)
    set(ARG_OUTPUT_NAME ${TARGET_NAME})
  endif()

  # Create the executable
  add_executable(${TARGET_NAME} ${ARG_SOURCES})

  # Set output name
  set_target_properties(${TARGET_NAME} PROPERTIES
    OUTPUT_NAME ${ARG_OUTPUT_NAME}
    SUFFIX ".wasm"
  )

  # Build export flags
  if(ARG_EXPORTS)
    list(TRANSFORM ARG_EXPORTS PREPEND "_")
    string(REPLACE ";" "','" EXPORTS_STR "${ARG_EXPORTS}")
    target_link_options(${TARGET_NAME} PRIVATE
      "-s EXPORTED_FUNCTIONS=['_malloc','_free','${EXPORTS_STR}']"
    )
  else()
    target_link_options(${TARGET_NAME} PRIVATE
      "-s EXPORTED_FUNCTIONS=['_malloc','_free']"
    )
  endif()
endfunction()

# Message to confirm toolchain is loaded
message(STATUS "Functions.do Emscripten Toolchain loaded")
message(STATUS "  EMSDK_ROOT: ${EMSDK_ROOT}")
message(STATUS "  C Compiler: ${CMAKE_C_COMPILER}")
message(STATUS "  C++ Compiler: ${CMAKE_CXX_COMPILER}")
